server:
  servlet:
    context-path: /swagger
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/swagger?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://106.15.91.232:3306/swagger?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: zwx_1998
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.swagger.entity
logging:
  config: classpath:log4j2.yml
